version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: notes_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/postgres-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
